TEXT_INPUT_DIR = "tests/data/website_text"
EXTRACTED_RECIPE_DIR = "tests/data/recipe_json"
ENRICHED_RECIPE_DIR = "tests/data/enriched_recipe_json"
WEIGHT_EST_DIR = "tests/data/weight_estimates_json"
CO2_EMISSIONS_DIR = "tests/data/co2_emissions_json"
