steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Pull image for caching if exists"
    entrypoint: "bash"
    args: ["-c", "docker pull $_IMAGE_NAME || exit 0"]
  - name: "gcr.io/cloud-builders/docker"
    id: "Build image"
    args: ["build", "-t", "$_IMAGE_NAME", "--cache-from", "$_IMAGE_NAME", "."]
    automapSubstitutions: true
  - name: "gcr.io/cloud-builders/docker"
    id: "Push image"
    args: ["push", "$_IMAGE_NAME"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy to Cloud Run"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - foodprint-frontend
      - --allow-unauthenticated
      - --image=$_IMAGE_NAME
      - --region=europe-north1
      - --platform=managed
      - --port=3000
      - --max-instances=1
      - --min-instances=0
      - --memory=512Mi
      - --update-secrets=API_BASE=FoodprintBackendAPI:latest
images:
  - "$_IMAGE_NAME"
substitutions:
  _IMAGE_NAME: europe-north1-docker.pkg.dev/${PROJECT_ID}/foodprint/foodprint-frontend:latest
options:
  dynamicSubstitutions: true
