name: Continuous intregration of Recipe CO2 Estimator app

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  ci-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install poetry v.2.1.2
        run: pipx install poetry==2.1.2

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: "poetry"

      - name: Install dependencies
        run: |
          make install

      - name: Check linting
        run: |
          make lint

      - name: Format code
        run: |
          make format

      - name: Run type checking
        run: |
          make type-check

      - name: Run tests
        run: |
          make test
        env:
          MODEL_VENDOR: google
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          USE_CACHE: false
          STORE_IN_CACHE: false
